/* tslint:disable */
/* eslint-disable */
/**
 * Smart Home API
 * OAS for Smart Home API
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrNotFound
 */
export interface ErrNotFound {
    /**
     * 
     * @type {string}
     * @memberof ErrNotFound
     */
    errMsg: string;
}

/**
 * Check if a given object implements the ErrNotFound interface.
 */
export function instanceOfErrNotFound(value: object): value is ErrNotFound {
    if (!('errMsg' in value) || value['errMsg'] === undefined) return false;
    return true;
}

export function ErrNotFoundFromJSON(json: any): ErrNotFound {
    return ErrNotFoundFromJSONTyped(json, false);
}

export function ErrNotFoundFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrNotFound {
    if (json == null) {
        return json;
    }
    return {
        
        'errMsg': json['err_msg'],
    };
}

export function ErrNotFoundToJSON(json: any): ErrNotFound {
    return ErrNotFoundToJSONTyped(json, false);
}

export function ErrNotFoundToJSONTyped(value?: ErrNotFound | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'err_msg': value['errMsg'],
    };
}

